version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/homekey
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - homekey-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=homekey
    ports:
      - "5432:5432"
    networks:
      - homekey-network

volumes:
  postgres_data:

networks:
  homekey-network:
    driver: bridge
